### ISSUE TITLE
Enchancements - Docs Update, Quick Actions Patch and Unit Tests Part-Refactoring.

### ISSUE THREAD

**Issue by yPiuro** [Notliam99/TestingApi#23]
**Docs UPDATE**
Update docs to include new check command and update it with a teaser,

**Actions**
Updated check command.

**Unit Tests**
Part-Refactoring of unit tests to use a functions instead of repeating similar code.

**_D.R.Y_**

**Comment by Notliam99** [comment]
Next time can you make each change like (docs, actions, code) to there own branches and PR's
