### ISSUE TITLE
BUG - Github actions Release build artifact

### ISSUE THREAD

**Issue by yPiuro** [Notliam99/TestingApi#28]
**Describe the bug**
Actions fails because it does not have enough permissions.

**To Reproduce**
N/A

LOOK AT ACTIONS LOGS.

**Expected behavior**
Not crash and finish action jobs.

**Additional context**
@Notliam99 Just go to [https://github.com/Notliam99/TestingApi/settings/actions](https://github.com/Notliam99/TestingApi/settings/actions
) and give actions write perms.

**Comment by Notliam99** [comment]
haha i see whats the issue ill fix it

**Comment by Notliam99** [comment]
Fixed 👍🏿
